CREATE TABLE Team (
  Id BIGINT PRIMARY KEY IDENTITY(1, 1),
  Name NVARCHAR(64) NOT NULL UNIQUE,
  DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)

CREATE TABLE Season (
  Id BIGINT PRIMARY KEY IDENTITY(1, 1),
  DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)

CREATE TABLE SeasonMembership (
  TeamId BIGINT REFERENCES Team (Id),
  SeasonId BIGINT REFERENCES Season (Id),
  PRIMARY KEY (TeamId, SeasonId)
)