CREATE TABLE Team (
  Id BIGINT PRIMARY KEY IDENTITY(1, 1),
  Name NVARCHAR(64) NOT NULL UNIQUE,
  DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)

CREATE TABLE Season (
  Id BIGINT PRIMARY KEY IDENTITY(1, 1),
  DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)

CREATE TABLE SeasonMatch (
  Id BIGINT PRIMARY KEY IDENTITY(1, 1),
  TeamOneId BIGINT REFERENCES Team (Id),
  TeamTwoId BIGINT REFERENCES Team (Id),
  DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)

CREATE TABLE SeasonDivision (
  Id BIGINT PRIMARY KEY IDENTITY(1, 1),
  SeasonId BIGINT REFERENCES Season (Id),
  DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)

CREATE TABLE SeasonDivisionMembership (
  TeamId BIGINT REFERENCES Team (Id),
  SeasonDivisionId BIGINT REFERENCES SeasonDivision (Id),
  PRIMARY KEY (TeamId, SeasonDivisionId)
)