CREATE TABLE Team (
  Id BIGINT PRIMARY KEY IDENTITY(1, 1),
  Name TEXT NOT NULL,
  DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)

CREATE TABLE RegularSeasonWeek (
  Id BIGINT PRIMARY KEY IDENTITY(1, 1),
  DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)

CREATE TABLE RegularSeasonMatch (
  Id BIGINT PRIMARY KEY IDENTITY(1, 1),
  Week BIGINT REFERENCES RegularSeasonWeek (Id),
  TeamA BIGINT REFERENCES Team (Id),
  TeamB BIGINT REFERENCES Team (Id),
  DateCreated DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)